### ISSUE TITLE
conflict with Amasty extensions!

### ISSUE THREAD

**Issue by sIiiS** [cgzhang/Rayfox_Catalog#4]
First I want to thank you for your great extension

As I test, if we enabled "[Amasty Improved Layered Navigation](https://amasty.com/improved-layered-navigation.html)" or "[Amasty Improved Sorting](https://amasty.com/improved-sorting.html)" extensions and then use your extension too and enable it for sorting products and we have configurable products, then we got error in categories!
If disable your extension or disable one of the Amasty's extensions, then errors gone and category load fine!
You can see code below(error that I got it)

> SQLSTATE[42S22]: Column not found: 1054 Unknown column 'stock_status.stock_status' in 'field list', query was: select SUM(stock.salable) as in_stock, COUNT(stock.salable) - SUM(stock.salable) as out_stock from (SELECT `stock_status`.`stock_status` AS `salable` FROM `catalog_product_entity` AS `e`
 INNER JOIN `catalog_category_product_index` AS `cat_index` ON cat_index.product_id=e.entity_id AND cat_index.store_id=1 AND cat_index.visibility IN(2, 4) AND cat_index.category_id = '44' AND cat_index.is_parent=1
 INNER JOIN `catalog_product_index_price` AS `price_index` ON price_index.entity_id = e.entity_id AND price_index.website_id = '1' AND price_index.customer_group_id = 0
 LEFT JOIN `cataloginventory_stock_status` AS `cisi` ON (cisi.product_id=e.entity_id) AND (cisi.website_id = '1')) as stock

**Comment by razbakov** [comment]
Hello @sIiiS, thank you for reporting the issue. 
Unfortunately we are not developers of this module, we only pushed it to github and added composer. 

Module comes from https://www.magentocommerce.com/magento-connect/sort-products-automatically-sort-by-stock.html

**Comment by cgzhang** [comment]
should be fixed on version 0.2.4.1

**Comment by razbakov** [comment]
@cgzhang would you mind to use [semver](http://semver.org/) and name next bugfix version as 0.2.5?

**Comment by sIiiS** [comment]
issue still available in version 0.2.5 !

`SQLSTATE[42S22]: Column not found: 1054 Unknown column 'stock_status.stock_status' in 'field list', query was: select SUM(stock.salable) as in_stock, COUNT(stock.salable) - SUM(stock.salable) as out_stock from (SELECT`stock_status`.`stock_status`AS`salable`FROM`catalog_product_entity`AS`e`
 INNER JOIN`catalog_category_product_index`AS`cat_index`ON cat_index.product_id=e.entity_id AND cat_index.store_id=1 AND cat_index.visibility IN(2, 4) AND cat_index.category_id = '7'
 INNER JOIN`catalog_product_index_price`AS`price_index`ON price_index.entity_id = e.entity_id AND price_index.website_id = '1' AND price_index.customer_group_id = 0
 LEFT JOIN`cataloginventory_stock_status`AS`cisi`ON (cisi.product_id=e.entity_id) AND (cisi.website_id = '1')
 INNER JOIN`catalog_product_index_eav`AS`manufacturer_idx`ON manufacturer_idx.entity_id = e.entity_id AND manufacturer_idx.attribute_id = '81' AND manufacturer_idx.store_id = 1 AND manufacturer_idx.value IN('100')) as stock`

**Comment by cgzhang** [comment]
Please try to debug helper function checkFieldExisted , to check if stock_status field or cataloginventory_stock_status tables already joined, if yes, skip my joinTable code.
